# Generated by Django 4.2.4 on 2023-11-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anony', '0004_alter_practical_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practical_feedback',
            name='comment',
            field=models.TextField(default='comment'),
        ),
    ]
