# Generated by Django 4.2.4 on 2023-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operat', '0003_alter_mapfaculty_practical_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_year',
            fields=[
                ('academic_year', models.IntegerField(primary_key=True, serialize=False)),
                ('current_bool', models.BooleanField(default=False)),
            ],
        ),
    ]
